memo_app/config/routes.rb
Rails.application.routes.draw do
  # get 'memos/index'
  # get 'memos/show'
  # get 'memos/new'
  # get 'memos/edit'
  root to: 'memos#index'
  resources :memos
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

memo_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

memo_app/app/models/memo.rb
class Memo < ApplicationRecord
end

memo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

memo_app/app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    @memos = Memo.all
  end

  def show
    @memo = Memo.find(params[:id])
  end

  def new
    @memo = Memo.new #Memo:db create new taple
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    memo = Memo.find(params[:id])
    memo.update!(memo_params)
    redirect_to memos_url, notice: "メモ「#{memo.title}」を更新しました。"
  end

  def create
    memo = Memo.new(memo_params)
    memo.save!
    redirect_to memos_url, notice: "メモ「#{memo.title}」を登録しました。"
  end

  def destroy
    memo = Memo.find(params[:id])
    memo.destroy
    redirect_to memos_url, notice: "メモ「#{memo.title}」が削除されました。"
  end

  private

  def memo_params
    params.require(:memo).permit(:title,:content)
  end
end

memo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

memo_app/app/helpers/memos_helper.rb
module MemosHelper
end

memo_app/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MemoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Memo_app

    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

memo_app/app/views/memos/_form.html.slim
= form_with model: memo, local: true do |f|

    .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', id: 'memo_title'
    .form-group
        = f.label :content
        = f.text_area :content, rows: 5, class: 'form-control', id:'memo_content'
    = f.submit "更新", class: 'btn btn-primary'
    tb= link_to '削除', @memo, method: :delete, data: {confirm:"メモ「#{@memo.title}」を削除してもよろしいですか？"},class:'btn btn-danger'

memo_app/app/views/memos/edit.html.slim
h1= "メモ「#{@memo.title}」:編集"

.nav.justify-content-end
    = link_to '一覧' ,memos_path, class:'btn btn-success'

= render partial: 'form', locals: {memo: @memo}

/ = form_with model: @memo, local: true do |f|
/     .form-group
/         = f.label :title
/         = f.text_field :title, class: 'form-control', id: 'memo_title'
/     .form-group
/         = f.label :content
/         = f.text_area :content, rows: 5, class: 'form-control', id:'memo_content'
/     = f.submit "更新", class: 'btn btn-primary'

memo_app/app/views/memos/index.html.slim
h1 メモ一覧

= link_to '新しいメモ', new_memo_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
    thead.head-default
        tr
            th= Memo.human_attribute_name(:title)
            th= Memo.human_attribute_name(:created_at)
            th= Memo.human_attribute_name(:updated_at)
            th
        tboty
        / controllerで@memo = Memo.allで持ってきたやつ
        -   @memos.each do |memo|
            tr
                td= link_to memo.title ,memo
                td= memo.created_at
                td= memo.updated_at
                td
                  = link_to '編集',edit_memo_path(memo), class: 'btn btn-primary mr-3'
                  = link_to '削除',memo,method: :delete, data: {confirm:"メモ「#{memo.title}」を削除してもよろしいですか？"}, class: 'btn btn-danger'

memo_app/app/views/memos/new.html.slim
h1 新規メモ作成 

.nav.justify-content-end
    = link_to '一覧', memos_path, class: 'btn btn-success'
= render partial: 'form', locals: {memo:@memo}

/ = form_with model: @memo, local: true do |f|
/     .form-group
/         = f.label :title
/         = f.text_field :title, class: 'form-control', id: 'memo_title'
/     .form-group
/         = f.label :content
/         = f.text_area :content, rows: 5, class: 'form-control', id: 'memo_content'
/     =f.submit "追加", class: 'btn btn-primary'

memo_app/app/views/memos/show.html.slim
h1= @memo.title

.nav.justify-content-end
    = link_to '一覧', memos_path, class: 'btn btn-success'
/ human_attribute_name(: ~~~ ) はconfig/locales/ja.ymlより 
/ ~~~に当てはまる物を探して対応する文字を入れてくれる
table.table.table-hober
    tbody
        tr
            th= Memo.human_attribute_name(:id)
            td= @memo.id
        tr 
            th= Memo.human_attribute_name(:title)
            td= @memo.title
        tr
            th= Memo.human_attribute_name(:content)
            / td= simple_format(h(@memo.content), {}, sanitize: false, wrapper_tag: "div")
            / 改行を<br>へ変換してくれる

            td= simple_format(h(@memo.content), {}, sanitize: false, wrapper_tag: "div")
        tr
            th= Memo.human_attribute_name(:created_at)
            td= @memo.created_at
        tr
            th= Memo.human_attribute_name(:updated_at)
            td= @memo.updated_at
        tr
            th
            td
= link_to '編集', edit_memo_path, class: 'btn btn-primary mr-3'
= link_to '削除', @memo, method: :delete, data: {confirm:"メモ「#{@memo.title}」を削除してもよろしいですか？"},class:'btn btn-danger'